service: checkrun-test
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1

functions:
  checkrun-test:
    handler: src/index.handler
    environment:
      WEBHOOK_SECRET: ${ssm:/CHECK_RUN_TEST/WEBHOOK_SECRET~true}
      GITHUB_APP_ID: ${ssm:/CHECK_RUN_TEST/GITHUB_APP_ID~true} # ~trueでデコードする
      GITHUB_APP_PRIVATE_KEY: ${ssm:/CHECK_RUN_TEST/GITHUB_APP_PRIVATE_KEY~true}
    url: true # 関数URLを有効化

resources:
  Resources:
    webhookSecret:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /CHECK_RUN_TEST/WEBHOOK_SECRET
        Type: String
        Value: "dummy"
        Tags:
          ManagedBy: github_app_test
    githubAppId:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /CHECK_RUN_TEST/GITHUB_APP_ID
        Type: String
        Value: "dummy"
        Tags:
          ManagedBy: github_app_test
    githubAppPrivateKey:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /CHECK_RUN_TEST/GITHUB_APP_PRIVATE_KEY
        Type: SecureString
        Value: "dummy"
        Tags:
          ManagedBy: github_app_test
